In [130]:
import os

1. Import the directory of Mimic-iii showing every file

In [131]:
os.listdir()

['.ipynb_checkpoints', 'Ifrah_Notebook.ipynb']

In [132]:
import pandas as pd

In [133]:
df = pd.read_csv("~/workspace/osa_supervised_ml/data/raw/PATIENTS.csv")

df is defined as the PATIENTS file dataframe.

In [134]:
df

,ROW_ID,SUBJECT_ID,GENDER,DOB,DOD,DOD_HOSP,DOD_SSN,EXPIRE_FLAG
0,234,249,F,2075-03-13 00:00:00,NaN,NaN,NaN,0
1,235,250,F,2164-12-27 00:00:00,2188-11-22 00:00:00,2188-11-22 00:00:00,NaN,1
2,236,251,M,2090-03-15 00:00:00,NaN,NaN,NaN,0
3,237,252,M,2078-03-06 00:00:00,NaN,NaN,NaN,0
4,238,253,F,2089-11-26 00:00:00,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...
46515,31840,44089,M,2026-05-25 00:00:00,NaN,NaN,NaN,0
46516,31841,44115,F,2124-07-27 00:00:00,NaN,NaN,NaN,0
46517,31842,44123,F,2049-11-26 00:00:00,2135-01-12 00:00:00,2135-01-12 00:00:00,NaN,1
46518,31843,44126,F,2076-07-25 00:00:00,NaN,NaN,NaN,0
46519,31844,44128,M,2098-07-25 00:00:00,NaN,NaN,NaN,0

In [135]:
dx = pd.read_csv("~/workspace/osa_supervised_ml/data/raw/D_ICD_DIAGNOSES.csv")

dx is defined as the ICD DIAGNOSES with short and long titles dataframe.

In [136]:
dx

,ROW_ID,ICD9_CODE,SHORT_TITLE,LONG_TITLE
0,174,01166,TB pneumonia-oth test,"Tuberculous pneumonia [any form], tubercle bac..."
1,175,01170,TB pneumothorax-unspec,"Tuberculous pneumothorax, unspecified"
2,176,01171,TB pneumothorax-no exam,"Tuberculous pneumothorax, bacteriological or h..."
3,177,01172,TB pneumothorx-exam unkn,"Tuberculous pneumothorax, bacteriological or h..."
4,178,01173,TB pneumothorax-micro dx,"Tuberculous pneumothorax, tubercle bacilli fou..."
...,...,...,...,...
14562,14432,V7399,Scrn unspcf viral dis,Special screening examination for unspecified ...
14563,14433,V740,Screening for cholera,Screening examination for cholera
14564,14434,V741,Screening-pulmonary TB,Screening examination for pulmonary tuberculosis
14565,14435,V742,Screening for leprosy,Screening examination for leprosy (Hansen's di...
14566,14436,V743,Screening for diphtheria,Screening examination for diphtheria

In [137]:
dy = pd.read_csv("~/workspace/osa_supervised_ml/data/raw/DIAGNOSES_ICD.csv")

dy is defined as the Diagnoses codes mathcing the specific patient dataframe.

In [138]:
dy

        ROW_ID  SUBJECT_ID  HADM_ID  SEQ_NUM ICD9_CODE
0         1297         109   172335      1.0     40301
1         1298         109   172335      2.0       486
2         1299         109   172335      3.0     58281
3         1300         109   172335      4.0      5855
4         1301         109   172335      5.0      4254
...        ...         ...      ...      ...       ...
651042  639798       97503   188195      2.0     20280
651043  639799       97503   188195      3.0     V5869
651044  639800       97503   188195      4.0     V1279
651045  639801       97503   188195      5.0      5275
651046  639802       97503   188195      6.0      5569

[651047 rows x 5 columns]

In [139]:
sleep_apnea = dx[dx["LONG_TITLE"].str.lower().str.contains("sleep apnea")]

Every instance of sleep apnea in the long title of the ICD DIAGNOSES dx dataframe.

In [140]:
sleep_apnea

,ROW_ID,ICD9_CODE,SHORT_TITLE,LONG_TITLE
3115,3116,32720,Organic sleep apnea NOS,"Organic sleep apnea, unspecified"
3116,3117,32721,Prim central sleep apnea,Primary central sleep apnea
3118,3119,32723,Obstructive sleep apnea,Obstructive sleep apnea (adult)(pediatric)
3122,3123,32727,Cntrl sleep apnea ot dis,Central sleep apnea in conditions classified e...
3123,3124,32729,Organic sleep apnea NEC,Other organic sleep apnea
8970,8971,78051,Insomn w sleep apnea NOS,"Insomnia with sleep apnea, unspecified"
8972,8973,78053,Hypersom w slp apnea NOS,"Hypersomnia with sleep apnea, unspecified"
8976,8977,78057,Sleep apnea NOS,Unspecified sleep apnea

In [141]:
results = dy.merge(sleep_apnea, on = "ICD9_CODE", how = "inner")

Merging the dy Diagnoses codes matched with patients dataframes 
with sleep_apnea (Every instance of sleep apnea in the long title of the ICD DIAGNOSES dx dataframe.)
due to the shared ICD9_CODE column.

In [142]:
results

,ROW_ID_x,SUBJECT_ID,HADM_ID,SEQ_NUM,ICD9_CODE,ROW_ID_y,SHORT_TITLE,LONG_TITLE
0,1319,109,173633,9.0,32723,3119,Obstructive sleep apnea,Obstructive sleep apnea (adult)(pediatric)
1,673,85,112077,12.0,32723,3119,Obstructive sleep apnea,Obstructive sleep apnea (adult)(pediatric)
2,1005,109,126055,22.0,32723,3119,Obstructive sleep apnea,Obstructive sleep apnea (adult)(pediatric)
3,1051,109,131376,13.0,32723,3119,Obstructive sleep apnea,Obstructive sleep apnea (adult)(pediatric)
4,1068,109,135923,10.0,32723,3119,Obstructive sleep apnea,Obstructive sleep apnea (adult)(pediatric)
...,...,...,...,...,...,...,...,...
2982,501187,66532,197709,13.0,32727,3123,Cntrl sleep apnea ot dis,Central sleep apnea in conditions classified e...
2983,562580,80287,150457,5.0,32727,3123,Cntrl sleep apnea ot dis,Central sleep apnea in conditions classified e...
2984,562757,80308,174505,10.0,32727,3123,Cntrl sleep apnea ot dis,Central sleep apnea in conditions classified e...
2985,549215,77163,120851,12.0,78053,8973,Hypersom w slp apnea NOS,"Hypersomnia with sleep apnea, unspecified"
2986,578182,83578,188236,12.0,32720,3116,Organic sleep apnea NOS,"Organic sleep apnea, unspecified"

In [143]:
len(results["SUBJECT_ID"].unique())

2199

results.to_csv("/project/projectdirs/m1532/Projects_MVP/_datasets/MIMICIII_vocab/SA_mergedptcode.csv", index=True)

In [145]:
SA_onlysubjectvisitcodetitle = results[["SUBJECT_ID","HADM_ID","ICD9_CODE","SHORT_TITLE","LONG_TITLE"]]
SA_onlysubjectvisitcodetitle

,SUBJECT_ID,HADM_ID,ICD9_CODE,SHORT_TITLE,LONG_TITLE
0,109,173633,32723,Obstructive sleep apnea,Obstructive sleep apnea (adult)(pediatric)
1,85,112077,32723,Obstructive sleep apnea,Obstructive sleep apnea (adult)(pediatric)
2,109,126055,32723,Obstructive sleep apnea,Obstructive sleep apnea (adult)(pediatric)
3,109,131376,32723,Obstructive sleep apnea,Obstructive sleep apnea (adult)(pediatric)
4,109,135923,32723,Obstructive sleep apnea,Obstructive sleep apnea (adult)(pediatric)
...,...,...,...,...,...
2982,66532,197709,32727,Cntrl sleep apnea ot dis,Central sleep apnea in conditions classified e...
2983,80287,150457,32727,Cntrl sleep apnea ot dis,Central sleep apnea in conditions classified e...
2984,80308,174505,32727,Cntrl sleep apnea ot dis,Central sleep apnea in conditions classified e...
2985,77163,120851,78053,Hypersom w slp apnea NOS,"Hypersomnia with sleep apnea, unspecified"
2986,83578,188236,32720,Organic sleep apnea NOS,"Organic sleep apnea, unspecified"

In [146]:
len(SA_onlysubjectvisitcodetitle["HADM_ID"].unique())

2979

SA_onlysubjectvisitcodetitle.to_csv("/project/projectdirs/m1532/Projects_MVP/_datasets/MIMICIII_vocab/SA_onlysubjectvisitcodetitle.csv", index=True)

In [148]:
SA_uniqueonlysubjectvisitcodetitle = SA_onlysubjectvisitcodetitle.drop_duplicates(subset=['HADM_ID'])
SA_uniqueonlysubjectvisitcodetitle

,SUBJECT_ID,HADM_ID,ICD9_CODE,SHORT_TITLE,LONG_TITLE
0,109,173633,32723,Obstructive sleep apnea,Obstructive sleep apnea (adult)(pediatric)
1,85,112077,32723,Obstructive sleep apnea,Obstructive sleep apnea (adult)(pediatric)
2,109,126055,32723,Obstructive sleep apnea,Obstructive sleep apnea (adult)(pediatric)
3,109,131376,32723,Obstructive sleep apnea,Obstructive sleep apnea (adult)(pediatric)
4,109,135923,32723,Obstructive sleep apnea,Obstructive sleep apnea (adult)(pediatric)
...,...,...,...,...,...
2979,31237,152178,32727,Cntrl sleep apnea ot dis,Central sleep apnea in conditions classified e...
2980,31503,184692,32727,Cntrl sleep apnea ot dis,Central sleep apnea in conditions classified e...
2984,80308,174505,32727,Cntrl sleep apnea ot dis,Central sleep apnea in conditions classified e...
2985,77163,120851,78053,Hypersom w slp apnea NOS,"Hypersomnia with sleep apnea, unspecified"
2986,83578,188236,32720,Organic sleep apnea NOS,"Organic sleep apnea, unspecified"

SA_uniqueonlysubjectvisitcodetitle.to_csv("/project/projectdirs/m1532/Projects_MVP/_datasets/MIMICIII_vocab/SA_uniqueonlysubjectvisitcodetitle.csv", index=True)

Unique patients w sleep apnea diagnosis codes

In [150]:
dy

        ROW_ID  SUBJECT_ID  HADM_ID  SEQ_NUM ICD9_CODE
0         1297         109   172335      1.0     40301
1         1298         109   172335      2.0       486
2         1299         109   172335      3.0     58281
3         1300         109   172335      4.0      5855
4         1301         109   172335      5.0      4254
...        ...         ...      ...      ...       ...
651042  639798       97503   188195      2.0     20280
651043  639799       97503   188195      3.0     V5869
651044  639800       97503   188195      4.0     V1279
651045  639801       97503   188195      5.0      5275
651046  639802       97503   188195      6.0      5569

[651047 rows x 5 columns]

In [151]:
heart_failure428 = dy[dy["ICD9_CODE"].astype('str').str.startswith("428")]

In [152]:
heart_failure428

        ROW_ID  SUBJECT_ID  HADM_ID  SEQ_NUM ICD9_CODE
51        1511         115   114585     10.0      4280
67        1527         117   140784      5.0      4280
150       1610         124   138376     12.0     42833
153       1613         124   138376     15.0      4280
211       1671         130   198214      2.0      4280
...        ...         ...      ...      ...       ...
650879  638387       97144   109999     15.0      4280
650973  638481       97172   133092      5.0     42833
650977  638485       97172   133092      9.0      4280
650995  639751       97488   152542      7.0      4280
651016  639772       97488   161999     17.0      4280

[20676 rows x 5 columns]

In [153]:
len(heart_failure428["ICD9_CODE"].unique())

15

In [154]:
len(heart_failure428["SUBJECT_ID"].unique())

10154

In [155]:
heart_failurestring = dx[dx["LONG_TITLE"].str.lower().str.contains("heart failure")]
heart_failurestring

,ROW_ID,ICD9_CODE,SHORT_TITLE,LONG_TITLE
4299,4300,39891,Rheumatic heart failure,Rheumatic heart failure (congestive)
4304,4305,40200,Mal hyp ht dis w/o hf,Malignant hypertensive heart disease without h...
4305,4306,40201,Mal hypert hrt dis w hf,Malignant hypertensive heart disease with hear...
4306,4307,40210,Benign hyp ht dis w/o hf,Benign hypertensive heart disease without hear...
4307,4308,40211,Benign hyp ht dis w hf,Benign hypertensive heart disease with heart f...
4308,4309,40290,Hyp hrt dis NOS w/o hf,Unspecified hypertensive heart disease without...
4309,4310,40291,Hyp ht dis NOS w ht fail,Unspecified hypertensive heart disease with he...
4316,4317,40400,Mal hy ht/kd I-IV w/o hf,"Hypertensive heart and chronic kidney disease,..."
4317,4318,40401,Mal hyp ht/kd I-IV w hf,"Hypertensive heart and chronic kidney disease,..."
4318,4319,40402,Mal hy ht/kd st V w/o hf,"Hypertensive heart and chronic kidney disease,..."
4319,4320,40403,Mal hyp ht/kd stg V w hf,"Hypertensive heart and chronic kidney disease,..."
4320,4321,40410,Ben hy ht/kd I-IV w/o hf,"Hypertensive heart and chronic kidney disease,..."
4321,4322,40411,Ben hyp ht/kd I-IV w hf,"Hypertensive heart and chronic kidney disease,..."
4322,4323,40412,Ben hy ht/kd st V w/o hf,"Hypertensive heart and chronic kidney disease,..."
4323,4324,40413,Ben hyp ht/kd stg V w hf,"Hypertensive heart and chronic kidney disease,..."
4324,4325,40490,Hy ht/kd NOS I-IV w/o hf,"Hypertensive heart and chronic kidney disease,..."
4325,4326,40491,Hyp ht/kd NOS I-IV w hf,"Hypertensive heart and chronic kidney disease,..."
4326,4327,40492,Hy ht/kd NOS st V w/o hf,"Hypertensive heart and chronic kidney disease,..."
4327,4328,40493,Hyp ht/kd NOS st V w hf,"Hypertensive heart and chronic kidney disease,..."
4472,4473,4280,CHF NOS,"Congestive heart failure, unspecified"
4473,4474,4281,Left heart failure,Left heart failure
4474,4475,42820,Systolic hrt failure NOS,"Systolic heart failure, unspecified"
4475,4476,42821,Ac systolic hrt failure,Acute systolic heart failure
4476,4477,42822,Chr systolic hrt failure,Chronic systolic heart failure
4477,4478,42823,Ac on chr syst hrt fail,Acute on chronic systolic heart failure
4478,4479,42830,Diastolc hrt failure NOS,"Diastolic heart failure, unspecified"
4479,4480,42831,Ac diastolic hrt failure,Acute diastolic heart failure
4480,4481,42832,Chr diastolic hrt fail,Chronic diastolic heart failure
4481,4482,42833,Ac on chr diast hrt fail,Acute on chronic diastolic heart failure
4482,4483,42840,Syst/diast hrt fail NOS,"Combined systolic and diastolic heart failure,..."
4483,4484,42841,Ac syst/diastol hrt fail,Acute combined systolic and diastolic heart fa...
4484,4485,42842,Chr syst/diastl hrt fail,Chronic combined systolic and diastolic heart ...
4485,4486,42843,Ac/chr syst/dia hrt fail,Acute on chronic combined systolic and diastol...
4486,4487,4289,Heart failure NOS,"Heart failure, unspecified"

In [156]:
len(heart_failurestring["ICD9_CODE"].unique())

34

In [157]:
heart_failure428string= heart_failurestring[heart_failurestring["ICD9_CODE"].astype('str').str.startswith("428")]
heart_failure428string

,ROW_ID,ICD9_CODE,SHORT_TITLE,LONG_TITLE
4472,4473,4280,CHF NOS,"Congestive heart failure, unspecified"
4473,4474,4281,Left heart failure,Left heart failure
4474,4475,42820,Systolic hrt failure NOS,"Systolic heart failure, unspecified"
4475,4476,42821,Ac systolic hrt failure,Acute systolic heart failure
4476,4477,42822,Chr systolic hrt failure,Chronic systolic heart failure
4477,4478,42823,Ac on chr syst hrt fail,Acute on chronic systolic heart failure
4478,4479,42830,Diastolc hrt failure NOS,"Diastolic heart failure, unspecified"
4479,4480,42831,Ac diastolic hrt failure,Acute diastolic heart failure
4480,4481,42832,Chr diastolic hrt fail,Chronic diastolic heart failure
4481,4482,42833,Ac on chr diast hrt fail,Acute on chronic diastolic heart failure
4482,4483,42840,Syst/diast hrt fail NOS,"Combined systolic and diastolic heart failure,..."
4483,4484,42841,Ac syst/diastol hrt fail,Acute combined systolic and diastolic heart fa...
4484,4485,42842,Chr syst/diastl hrt fail,Chronic combined systolic and diastolic heart ...
4485,4486,42843,Ac/chr syst/dia hrt fail,Acute on chronic combined systolic and diastol...
4486,4487,4289,Heart failure NOS,"Heart failure, unspecified"

In [158]:
len(heart_failure428string["ICD9_CODE"].unique())

15

In [159]:
HF_mergedptcode = dy.merge(heart_failure428string, on = "ICD9_CODE", how = "inner")
HF_mergedptcode

,ROW_ID_x,SUBJECT_ID,HADM_ID,SEQ_NUM,ICD9_CODE,ROW_ID_y,SHORT_TITLE,LONG_TITLE
0,1511,115,114585,10.0,4280,4473,CHF NOS,"Congestive heart failure, unspecified"
1,1527,117,140784,5.0,4280,4473,CHF NOS,"Congestive heart failure, unspecified"
2,1613,124,138376,15.0,4280,4473,CHF NOS,"Congestive heart failure, unspecified"
3,1671,130,198214,2.0,4280,4473,CHF NOS,"Congestive heart failure, unspecified"
4,550,68,108329,10.0,4280,4473,CHF NOS,"Congestive heart failure, unspecified"
...,...,...,...,...,...,...,...,...
20671,459551,57491,144324,10.0,4289,4487,Heart failure NOS,"Heart failure, unspecified"
20672,490430,64192,160781,10.0,4289,4487,Heart failure NOS,"Heart failure, unspecified"
20673,624307,94223,157880,3.0,4289,4487,Heart failure NOS,"Heart failure, unspecified"
20674,621006,93541,160567,6.0,4289,4487,Heart failure NOS,"Heart failure, unspecified"
20675,627794,94961,102853,16.0,4289,4487,Heart failure NOS,"Heart failure, unspecified"

HF_mergedptcode.to_csv("/project/projectdirs/m1532/Projects_MVP/_datasets/MIMICIII_vocab/HF_mergedptcode.csv", index=True)

In [161]:
HF_onlysubjectvisitcodetitle = HF_mergedptcode[["SUBJECT_ID","HADM_ID","ICD9_CODE","SHORT_TITLE","LONG_TITLE"]]
HF_onlysubjectvisitcodetitle

,SUBJECT_ID,HADM_ID,ICD9_CODE,SHORT_TITLE,LONG_TITLE
0,115,114585,4280,CHF NOS,"Congestive heart failure, unspecified"
1,117,140784,4280,CHF NOS,"Congestive heart failure, unspecified"
2,124,138376,4280,CHF NOS,"Congestive heart failure, unspecified"
3,130,198214,4280,CHF NOS,"Congestive heart failure, unspecified"
4,68,108329,4280,CHF NOS,"Congestive heart failure, unspecified"
...,...,...,...,...,...
20671,57491,144324,4289,Heart failure NOS,"Heart failure, unspecified"
20672,64192,160781,4289,Heart failure NOS,"Heart failure, unspecified"
20673,94223,157880,4289,Heart failure NOS,"Heart failure, unspecified"
20674,93541,160567,4289,Heart failure NOS,"Heart failure, unspecified"
20675,94961,102853,4289,Heart failure NOS,"Heart failure, unspecified"

HF_onlysubjectvisitcodetitle.to_csv("/project/projectdirs/m1532/Projects_MVP/_datasets/MIMICIII_vocab/HF_onlysubjectvisitcodetitle.csv", index=True)

In [163]:
len(HF_onlysubjectvisitcodetitle["HADM_ID"].unique())

13608

In [164]:
HF_uniqueonlysubjectvisitcodetitle = HF_onlysubjectvisitcodetitle.drop_duplicates(subset=['HADM_ID'])
HF_uniqueonlysubjectvisitcodetitle

,SUBJECT_ID,HADM_ID,ICD9_CODE,SHORT_TITLE,LONG_TITLE
0,115,114585,4280,CHF NOS,"Congestive heart failure, unspecified"
1,117,140784,4280,CHF NOS,"Congestive heart failure, unspecified"
2,124,138376,4280,CHF NOS,"Congestive heart failure, unspecified"
3,130,198214,4280,CHF NOS,"Congestive heart failure, unspecified"
4,68,108329,4280,CHF NOS,"Congestive heart failure, unspecified"
...,...,...,...,...,...
20671,57491,144324,4289,Heart failure NOS,"Heart failure, unspecified"
20672,64192,160781,4289,Heart failure NOS,"Heart failure, unspecified"
20673,94223,157880,4289,Heart failure NOS,"Heart failure, unspecified"
20674,93541,160567,4289,Heart failure NOS,"Heart failure, unspecified"
20675,94961,102853,4289,Heart failure NOS,"Heart failure, unspecified"

In [172]:
HF_uniqueonlysubjectvisitcodetitle.columns.values

array(['SUBJECT_ID', 'HADM_ID', 'ICD9_CODE', 'SHORT_TITLE', 'LONG_TITLE'],
      dtype=object)

HF_uniqueonlysubjectvisitcodetitle.to_csv("/project/projectdirs/m1532/Projects_MVP/_datasets/MIMICIII_vocab/HF_uniqueonlysubjectvisitcodetitle.csv", index=True)

In [168]:
UniqueHADM_SA_HF = HF_uniqueonlysubjectvisitcodetitle.merge(SA_uniqueonlysubjectvisitcodetitle, on = "HADM_ID", how = "inner")
UniqueHADM_SA_HF

,SUBJECT_ID_x,HADM_ID,ICD9_CODE_x,SHORT_TITLE_x,LONG_TITLE_x,SUBJECT_ID_y,ICD9_CODE_y,SHORT_TITLE_y,LONG_TITLE_y
0,138,108120,4280,CHF NOS,"Congestive heart failure, unspecified",138,78057,Sleep apnea NOS,Unspecified sleep apnea
1,138,188284,4280,CHF NOS,"Congestive heart failure, unspecified",138,78057,Sleep apnea NOS,Unspecified sleep apnea
2,165,170252,4280,CHF NOS,"Congestive heart failure, unspecified",165,32723,Obstructive sleep apnea,Obstructive sleep apnea (adult)(pediatric)
3,156,199280,4280,CHF NOS,"Congestive heart failure, unspecified",156,78057,Sleep apnea NOS,Unspecified sleep apnea
4,351,174800,4280,CHF NOS,"Congestive heart failure, unspecified",351,78057,Sleep apnea NOS,Unspecified sleep apnea
...,...,...,...,...,...,...,...,...,...
1206,5752,115932,42832,Chr diastolic hrt fail,Chronic diastolic heart failure,5752,32723,Obstructive sleep apnea,Obstructive sleep apnea (adult)(pediatric)
1207,20728,102013,42832,Chr diastolic hrt fail,Chronic diastolic heart failure,20728,78057,Sleep apnea NOS,Unspecified sleep apnea
1208,21510,138332,42832,Chr diastolic hrt fail,Chronic diastolic heart failure,21510,78057,Sleep apnea NOS,Unspecified sleep apnea
1209,28887,163359,42832,Chr diastolic hrt fail,Chronic diastolic heart failure,28887,32723,Obstructive sleep apnea,Obstructive sleep apnea (adult)(pediatric)
1210,53309,147011,42832,Chr diastolic hrt fail,Chronic diastolic heart failure,53309,78057,Sleep apnea NOS,Unspecified sleep apnea

UniqueHADM_SA_HF.to_csv("/project/projectdirs/m1532/Projects_MVP/_datasets/MIMICIII_vocab/UniqueHADM_SA_HF.csv", index=True)

In [170]:
UniqueHADM_SA_HF["GOLD_STANDARD"] = 2
UniqueHADM_SA_HF

,SUBJECT_ID_x,HADM_ID,ICD9_CODE_x,SHORT_TITLE_x,LONG_TITLE_x,SUBJECT_ID_y,ICD9_CODE_y,SHORT_TITLE_y,LONG_TITLE_y,GOLD_STANDARD
0,138,108120,4280,CHF NOS,"Congestive heart failure, unspecified",138,78057,Sleep apnea NOS,Unspecified sleep apnea,2
1,138,188284,4280,CHF NOS,"Congestive heart failure, unspecified",138,78057,Sleep apnea NOS,Unspecified sleep apnea,2
2,165,170252,4280,CHF NOS,"Congestive heart failure, unspecified",165,32723,Obstructive sleep apnea,Obstructive sleep apnea (adult)(pediatric),2
3,156,199280,4280,CHF NOS,"Congestive heart failure, unspecified",156,78057,Sleep apnea NOS,Unspecified sleep apnea,2
4,351,174800,4280,CHF NOS,"Congestive heart failure, unspecified",351,78057,Sleep apnea NOS,Unspecified sleep apnea,2
...,...,...,...,...,...,...,...,...,...,...
1206,5752,115932,42832,Chr diastolic hrt fail,Chronic diastolic heart failure,5752,32723,Obstructive sleep apnea,Obstructive sleep apnea (adult)(pediatric),2
1207,20728,102013,42832,Chr diastolic hrt fail,Chronic diastolic heart failure,20728,78057,Sleep apnea NOS,Unspecified sleep apnea,2
1208,21510,138332,42832,Chr diastolic hrt fail,Chronic diastolic heart failure,21510,78057,Sleep apnea NOS,Unspecified sleep apnea,2
1209,28887,163359,42832,Chr diastolic hrt fail,Chronic diastolic heart failure,28887,32723,Obstructive sleep apnea,Obstructive sleep apnea (adult)(pediatric),2
1210,53309,147011,42832,Chr diastolic hrt fail,Chronic diastolic heart failure,53309,78057,Sleep apnea NOS,Unspecified sleep apnea,2

In [171]:
UniqueHADM_SA_HF.columns.values

array(['SUBJECT_ID_x', 'HADM_ID', 'ICD9_CODE_x', 'SHORT_TITLE_x',
       'LONG_TITLE_x', 'SUBJECT_ID_y', 'ICD9_CODE_y', 'SHORT_TITLE_y',
       'LONG_TITLE_y', 'GOLD_STANDARD'], dtype=object)

In [184]:
#UniqueHADM_SA_HF.rename(columns = {'SUBJECT_ID_x':'SUBJECT_ID'}, inplace = True)
UniqueHADM_SA_HF

In [128]:
HF_uniqueonlysubjectvisitcodetitle["GOLD_STANDARD"] = 1
HF_uniqueonlysubjectvisitcodetitle

/tmp/ipykernel_58192/708897597.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  HF_uniqueonlysubjectvisitcodetitle["GOLD_STANDARD"] = 1

,SUBJECT_ID,HADM_ID,ICD9_CODE,SHORT_TITLE,LONG_TITLE,GOLD_STANDARD
0,115,114585,4280,CHF NOS,"Congestive heart failure, unspecified",1
1,117,140784,4280,CHF NOS,"Congestive heart failure, unspecified",1
2,124,138376,4280,CHF NOS,"Congestive heart failure, unspecified",1
3,130,198214,4280,CHF NOS,"Congestive heart failure, unspecified",1
4,68,108329,4280,CHF NOS,"Congestive heart failure, unspecified",1
...,...,...,...,...,...,...
20671,57491,144324,4289,Heart failure NOS,"Heart failure, unspecified",1
20672,64192,160781,4289,Heart failure NOS,"Heart failure, unspecified",1
20673,94223,157880,4289,Heart failure NOS,"Heart failure, unspecified",1
20674,93541,160567,4289,Heart failure NOS,"Heart failure, unspecified",1
20675,94961,102853,4289,Heart failure NOS,"Heart failure, unspecified",1

In [129]:
SA_uniqueonlysubjectvisitcodetitle["GOLD_STANDARD"] = 0
SA_uniqueonlysubjectvisitcodetitle

/tmp/ipykernel_58192/1897573501.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  SA_uniqueonlysubjectvisitcodetitle["GOLD_STANDARD"] = 0

,SUBJECT_ID,HADM_ID,ICD9_CODE,SHORT_TITLE,LONG_TITLE,GOLD_STANDARD
0,109,173633,32723,Obstructive sleep apnea,Obstructive sleep apnea (adult)(pediatric),0
1,85,112077,32723,Obstructive sleep apnea,Obstructive sleep apnea (adult)(pediatric),0
2,109,126055,32723,Obstructive sleep apnea,Obstructive sleep apnea (adult)(pediatric),0
3,109,131376,32723,Obstructive sleep apnea,Obstructive sleep apnea (adult)(pediatric),0
4,109,135923,32723,Obstructive sleep apnea,Obstructive sleep apnea (adult)(pediatric),0
...,...,...,...,...,...,...
2979,31237,152178,32727,Cntrl sleep apnea ot dis,Central sleep apnea in conditions classified e...,0
2980,31503,184692,32727,Cntrl sleep apnea ot dis,Central sleep apnea in conditions classified e...,0
2984,80308,174505,32727,Cntrl sleep apnea ot dis,Central sleep apnea in conditions classified e...,0
2985,77163,120851,78053,Hypersom w slp apnea NOS,"Hypersomnia with sleep apnea, unspecified",0
2986,83578,188236,32720,Organic sleep apnea NOS,"Organic sleep apnea, unspecified",0

In [196]:
hf = HF_uniqueonlysubjectvisitcodetitle[["SUBJECT_ID","HADM_ID"]]
sa = SA_uniqueonlysubjectvisitcodetitle[["SUBJECT_ID","HADM_ID"]]
hf["hf"] = True 
sa["sa"] = True
hf_sa = hf.merge(sa, on=["SUBJECT_ID", "HADM_ID"], how = "outer")
hf_sa = hf_sa.fillna(False)
hf_sa["hf_sa"] = hf_sa["hf"] & hf_sa["sa"]
hf_sa["hf_sa"].sum()
# hf_sa.to_csv("/project/projectdirs/m1532/Projects_MVP/_datasets/MIMICIII_vocab/labels.csv", index=True)

/tmp/ipykernel_58192/1854464289.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hf["hf"] = True
/tmp/ipykernel_58192/1854464289.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sa["sa"] = True

1211

In [200]:
dn = pd.read_csv("~/workspace/osa_supervised_ml/data/raw/NOTEEVENTS.csv")

/tmp/ipykernel_58192/1203950853.py:1: DtypeWarning: Columns (4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  dn = pd.read_csv("~/workspace/osa_supervised_ml/data/raw/NOTEEVENTS.csv")

In [201]:
hf_sa_noteevents = hf_sa.merge(dn, on=["SUBJECT_ID","HADM_ID"], how = "inner")
hf_sa_noteevents

,SUBJECT_ID,HADM_ID,hf,sa,hf_sa,ROW_ID,CHARTDATE,CHARTTIME,STORETIME,CATEGORY,DESCRIPTION,CGID,ISERROR,TEXT
0,115,114585,True,False,False,28391,2194-11-13,NaN,NaN,Discharge summary,Report,NaN,NaN,Admission Date: [**2194-10-16**] ...
1,115,114585,True,False,False,82745,2194-10-18,NaN,NaN,Echo,Report,NaN,NaN,PATIENT/TEST INFORMATION:\nIndication: Left ve...
2,115,114585,True,False,False,206205,2194-11-01,NaN,NaN,ECG,Report,NaN,NaN,Baseline artifact\nSinus rhythm\nProbable norm...
3,115,114585,True,False,False,206206,2194-10-25,NaN,NaN,ECG,Report,NaN,NaN,Sinus tachycardia\nPossible anterior infarct -...
4,115,114585,True,False,False,206207,2194-10-24,NaN,NaN,ECG,Report,NaN,NaN,Sinus rhythm. Non-specific inferior ST-T wave ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
533306,77163,120851,False,True,False,1102762,2175-10-12,2175-10-12 13:59:00,NaN,Radiology,TUNNELED W/ PORT,NaN,NaN,[**2175-10-12**] 1:59 PM\n PORT PLACEMENT SCH ...
533307,77163,120851,False,True,False,701664,2175-10-10,2175-10-10 06:30:00,2175-10-10 06:56:15,Physician,Physician Resident Progress Note,19796.0,NaN,TITLE:\n Chief Complaint:\n 24 Hour Events...
533308,83578,188236,False,True,False,49820,2150-05-09,NaN,NaN,Discharge summary,Report,NaN,NaN,Admission Date: [**2150-5-3**] D...
533309,83578,188236,False,True,False,59205,2150-05-09,NaN,NaN,Discharge summary,Addendum,NaN,NaN,"Name: [**Known lastname 12086**],[**Known fir..."
533310,83578,188236,False,True,False,300879,2150-05-04,NaN,NaN,ECG,Report,NaN,NaN,Sinus rhythm with atrial premature contraction...

In [208]:
hf_sa_noteeventsexport= hf_sa_noteevents[["SUBJECT_ID","HADM_ID", "TEXT"]]
hf_sa_noteeventsexport = hf_sa_noteeventsexport.groupby(["SUBJECT_ID", "HADM_ID"]).sum().reset_index()
hf_sa_noteeventsexport
# hf_sa_noteeventsexport.to_csv("/project/projectdirs/m1532/Projects_MVP/_datasets/MIMICIII_vocab/inputs.csv", index=True)

<b> <h1> TASK: SEARCH FOR SLEEP APNEA IN NOTE EVENTS <h1> <b>

In [ ]:
dn = pd.read_csv("NOTEEVENTS.csv")

No idea what this error means. Seems I can just ignore it. Ask Raf to make sure.

In [ ]:
dn

results = dy.merge(sleep_apnea, on = "ICD9_CODE", how = "inner") FOLLOW THIS

In [ ]:
sa_in_ne = dn.merge(results, on = "SUBJECT_ID", how = "inner")

Merging the dn Note events dataframe with results (patients w sleep apnea diagnosis codes) due to the shared SUBJECT_ID column.

In [ ]:
sa_in_ne

In [ ]:
len(sa_in_ne["SUBJECT_ID"].unique())

10 less than results

Correct?

<b> <h1> TASK: Merge text and results and see subject and hadm <h1> <b>

sa_in_ne = dn.merge(results, on = "SUBJECT_ID", how = "inner") FOLLOW THIS

In [ ]:
ne_and_results_hadm = dn.merge(results, on = "HADM_ID", how = "inner")

HADM_ID = Admitted in-patient hospital admission

In [ ]:
ne_and_results_hadm

Looks so wrong!

In [ ]:
len(ne_and_results_hadm["HADM_ID"].unique())

In [ ]:
sa_in_ne2 = dn[dn["TEXT"].str.lower().str.contains("sleep apnea")]

sa_in_ne2 = dn[dn["TEXT"].str.lower().str.contains(r"^sleep apnea")]

In [ ]:
sa_in_ne2

In [ ]:
len(results["SUBJECT_ID"].unique())

= Unique patients that were assigned sleep apnea diagnosis codes

In [ ]:
len(sa_in_ne2["SUBJECT_ID"].unique())

= Unique patients that had sleep apnea mentioned in the text of their Note events

In [ ]:
len(results["HADM_ID"].unique())

= Unique hospital admissions of patients that were assigned sleep apnea diagnosis codes

In [ ]:
len(sa_in_ne2["HADM_ID"].unique())

= Unique hospital admissions that had sleep apnea mentioned in the text of their Note events

How many patients overlap btw results and sa_in_ne2? Good example to use as ground truths. Coded and noted.

Codes used more on how to bill a patient.

Information retrieval research

Assess sensitivity and specificity detection of a classifier. How would you measure this? of the ICD code.
Can we increase sensitivity by looking at text of the note?

<b> Traditional NLP techniques <b>

keyword search (contains) engram (n value gram word)

Regex: match a more complicated expression of characters
(structure of document

Modifiers
Check if text is checking for patient not for family etc. 
Parsing grammatically ex. subject of sentence is patient or another reason? Parse tree.
Check for negation as well. (not, no, not at risk)
Get history of patient.

sleep apnea. how its written? symptoms? how theyre written?

<b> ML NLP <b>

1. Bag of words(treat sentence as collection of single words or characters) doc=array of words engrams in doc
see which words are most important(redundancy of words)
simple: logistic regression (each instance, increase likelihood? graph)

2. Fasttext (think of words in local neighborhoods) likelihood of distance of words between each other.
window, x words away from these 2 words, (word embeddings) DL

3. Transformers: trying to predict next word or which word is missing from a sentence. Looks at the whole sentence instead of window. BERT snd GPT. #parameters shows how complicated model is.

<b> goals <b>

1. build a vocabulary of how sleep apnea is described in medical text AND symptoms of sleep apnea
2. Build a rule based system for detecting sleep apnea if keywords arent good enough. (rule out negations) 
    Use Spacey bc comes w parsers
3. Make embeddings for making 

good way to detecting sa and symptoms
running your programs on a HPC

<b> Next week <b>

Learn about spacey in results and sa_in_ne2
Take 10 random texts from both (.sample in pandas)
    Find sentences w sleep apnea using reg ex (.str.findall)

Use spacey to parse sentence and get POS of each word
Continue reading of fasttext so we can train fasttext model

In [ ]:
r = results.sample(n=10)

In [ ]:
r

In [ ]:
s = sa_in_ne2.sample(n=10)

In [ ]:
s

In [ ]:
import re
result = s.TEXT.str.findall('sleep apnea', flags=re.IGNORECASE)

In [ ]:
result.reset_index()

r.str.findall('sleep apnea', flags=re.IGNORECASE)

import re
txt = r[["LONG_TITLE"]]
r_sa_sent = re.findall("sleep apnea", txt)
print(r_sa_sent)

In [ ]:
r['new_column'] = r.LONG_TITLE.str.findall('sleep apnea')

In [ ]:
r

In [ ]:
s['new_column'] = s.TEXT.str.findall('sleep apnea', flags=re.IGNORECASE)

In [ ]:
s

In [ ]:
import re
result = s.TEXT.str.findall('[^.]*sleep[^.]*\.', flags=re.IGNORECASE)

In [ ]:
result = s.TEXT.str.findall('.{16}sleep apnea.*\.', flags=re.IGNORECASE)

In [ ]:
result

In [ ]:
result = s.TEXT.str.findall('r"(?<!\w\.\w.)(?<![A-Z][a-z]\.)(?<=\.|\?|!)\s"', flags=re.IGNORECASE)

In [ ]:
result

import re
for x in s.TEXT:
    print (x + '', end="")

remove ! to see TEXT for first random in s

In [ ]:
s.index

In [ ]:
s.reset_index().loc[0, "TEXT"]

In [ ]:
import spacy
from spacy.matcher import PhraseMatcher

text = s.reset_index().loc[0, "TEXT"]

nlp = spacy.load("en_core_web_sm")

phrase_matcher = PhraseMatcher(nlp.vocab)
phrases = ['sleep apnea', 'OSA','slp apnea', 'SLEEP APNEA', 'Sleep apnea', 'Sleep Apnea']
patterns = [nlp(text) for text in phrases]
phrase_matcher.add('AI', None, *patterns)

doc = nlp(text)

for sent in doc.sents:
    for match_id, start, end in phrase_matcher(nlp(sent.text)):
        if nlp.vocab.strings[match_id] in ["AI"]:
            print(sent.text)
            print("next")
def sleep_apnea_matcher(TEXT):
    matches = []
    for sent in doc.sents:
        for match_id, start, end in phrase_matcher(nlp(sent.text)):
            if nlp.vocab.strings[match_id] in ["AI"]:
                matches.append(sent.text)
    return matches

In [ ]:
spacy.cli.download("en_core_web_sm")

import spacy
from spacy.matcher import PhraseMatcher

text = """I like tomtom and I cannot lie. In computer science, artificial intelligence (AI), sometimes called machine intelligence, is intelligence demonstrated by machines, unlike the natural intelligence displayed by humans and animals.  Leading AI textbooks define the field as the study of "intelligent agents": any device that perceives its  environment and takes actions that maximize its chance of successfully achieving its goals.[1] Colloquially,  the term "artificial intelligence" is often used to describe machines (or computers) that mimic "cognitive"  functions that humans associate with the human mind, such as "learning" and "problem solving".[2] """

nlp = spacy.load("en_core_web_sm")

phrase_matcher = PhraseMatcher(nlp.vocab)
phrases = ['machine learning', 'artificial intelligence']
patterns = [nlp(text) for text in phrases]
phrase_matcher.add('AI', None, *patterns)

doc = nlp(text)

for sent in doc.sents:
    for match_id, start, end in phrase_matcher(nlp(sent.text)):
        if nlp.vocab.strings[match_id] in ["AI"]:
            print(sent.text)
            print("next")

<b> <h1>  TASK: Create table for sa_in_ne2 with columns SUBJECT_ID, HADM_ID,ROW_ID, SNIPPET_ID, SNIPPET<h1> <b>

In [ ]:
sa_in_ne2

In [ ]:
dataset_table = sa_in_ne2[["SUBJECT_ID","HADM_ID","ROW_ID", "TEXT"]]

In [ ]:
dataset_table

#dataset_table = pd.DataFrame({'Snippet_ID': [1, 2]})
#dataset_table

In [ ]:
dataset_table["TEXT"] = dataset_table["TEXT"].apply(sleep_apnea_matcher)

In [ ]:
dataset_table = dataset_table.explode("TEXT", ignore_index=True)
#dataset_table['SNIPPET_ID'] = dataset_table.index
#dataset_table.index.name = "Index"
#dataset_table.index.name = np.arange(1,len(dataset_table)+1) 
#dataset_table.set_index('Index', inplace=True)
print(dataset_table.head())
len(dataset_table["TEXT"].unique())

In [ ]:
for x in dataset_table["TEXT"][0:10]:
    print(x)

In [ ]:
def split_in_sent(text):
    text = dataset_table.reset_index().loc[0,"TEXT"]
    doc = nlp(text)
    return [str(sent).strip() for sent in doc.sents]

split_in_sent(text)

In [ ]:
def split_in_sent(text):
    text = dataset_table["TEXT"]
    doc = nlp(text)
    return [str(sent).strip() for sent in doc.sents]

split_in_sent(text)

In [ ]:
def split_in_sent(text):
    for i in dataset_table:
        text = dataset_table.reset_index().loc[i, "TEXT"]
        doc = nlp(text)
        return [str(sent).strip() for sent in doc.sents]

split_in_sent(text)

[sent.text for sent in nlp(text).sents]

this works too but a bit too messy

In [ ]:
dataset_table['new_column'] = dataset_table.TEXT.str.findall('sleep apnea', flags=re.IGNORECASE)

In [ ]:
dataset_table

Raf's expected output
SUBJECT_ID,HADM_ID,ROW_ID,SNIPPET_ID,SNIPPET
01929,83747,019283,0,"this patient has sleep apnea"
01929,83747,019283,1,"this patient has had a history of sleep apnea"
01921,7347,012483,0,"this patient doesn't got sleep apnea"

Now: extract text into separate row sentences

In [ ]:
dataset_table['SNIPPET'] = str(split_in_sent(text))
dataset_table

In [ ]:
dataset_table.head()

In [ ]:
Something's wrong. 
My split_in_sent function only works on the first

To do: export tables as csv files and put in workspace. ref github raf repo and paper.terminal tutorial.

In [ ]:
is there useful clues around sa to see if the patient has another symptom related to it. use supervised learning from a dataset. use model to develop a set of rules to use on the VA data. looking to find symptoms to also diagnose CVD.

In [ ]:
sa_in_ne2.to_csv('sa_in_ne2.csv')

In [ ]:
dataset_table.to_csv('dataset_table.csv')

In [ ]:
pd.read_csv('new_table.csv')

In [ ]:
to use python3 file in terminal: load python3, activate conda env, run scripts.

# import pandas as pd
# dl = pd.read_csv("~/workspace/osa_supervised_ml/data/intermediate_data_files/unigram_ne1(head1).csv")
# # dl.columns=['unigram','nb_times']
# # dl.to_csv("~/workspace/osa_supervised_ml/data/intermediate_data_files/unigram_ne1(head1).csv", index=True)
# dl

In [8]:
import pandas as pd
dl = pd.read_csv("~/workspace/osa_supervised_ml/data/intermediate_data_files/unigram_ne1(head1).csv")
dl = dl.drop(columns="Unnamed: 0")
dl.to_csv("~/workspace/osa_supervised_ml/data/intermediate_data_files/unigram_ne1(head1).csv", index=True)

In [9]:
dl

         unigram  nb_times
0             11         1
1             12         2
2             16         1
3           1775         1
4           1776         1
..           ...       ...
59        showed         2
60         sized         1
61       studies         2
62           t10         1
63  tuberculosis         1

[64 rows x 2 columns]

In [40]:
import pandas as pd
dtetra5 = pd.read_csv("~/workspace/osa_supervised_ml/data/intermediate_data_files/tetragram_ne1(head5).csv")
# dtetra5.columns=['tetragram','nb_times']
dtetra5 = dtetra5.drop(columns="Unnamed: 0")
dtetra5
print (dtetra5.columns[1])
# dtetra5.to_csv("~/workspace/osa_supervised_ml/data/intermediate_data_files/tetragram_ne1(head5).csv", index=True)

nb_times

In [5]:
import pandas as pd
dn = pd.read_csv("~/workspace/osa_supervised_ml/data/raw/NOTEEVENTS.csv")
len(dn["TEXT"].unique())

/tmp/ipykernel_58192/545721432.py:2: DtypeWarning: Columns (4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  dn = pd.read_csv("~/workspace/osa_supervised_ml/data/raw/NOTEEVENTS.csv")

2023185

In [8]:
(2023185)/10

202318.5

In [9]:
202319*2

404638

In [10]:
202319*3

606957

In [11]:
202319*4

809276

In [12]:
202319*5

1011595

In [13]:
202319*6

1213914

In [14]:
202319*7

1416233

In [15]:
202319*8

1618552

In [17]:
202319*9

1820871

In [18]:
202319*10

2023190

In [3]:
import pandas as pd
dm = pd.read_csv("/project/projectdirs/m1532/Projects_MVP/_datasets/MIMICIII_vocab/MIMICIII_TRIGRAMS.csv")
len(dm)
dm.head(10)

                                            trigrams  counts
0                              clip number radiology  592423
1  ______________________________________________...  581114
2                                   clip clip number  553445
3                         hospital medical condition  495371
4  ______________________________________________...  495280
5                                       year old man  330403
6                                     year old woman  242161
7                                           mg dl mg  232169
8                                      mg tablet sig  183522
9                                  chest portable ap  181358

In [4]:
print(dm[dm['trigrams']=='periods apnea obstructive'])

                          trigrams  counts
5883961  periods apnea obstructive       5

In [49]:
print(dm[dm['trigrams']=='requirement obstructive sleep'])

                              trigrams  counts
3971129  requirement obstructive sleep       7

In [3]:
import pandas as pd
dt = pd.read_csv("/project/projectdirs/m1532/Projects_MVP/_datasets/MIMICIII_vocab/twelvthmodel.csv")
dt = dt.sort_values("osa_coef", ascending=False)
dt[["trigrams", "osa_coef", "hf_osa_coef", "hf_coef"]].head(50)

                                trigrams  osa_coef  hf_osa_coef   hf_coef
0                  sleep apnea discharge  0.559178     0.532419 -1.091598
1                         hx sleep apnea  0.518961     0.048664 -0.567626
2              disease obstructive sleep  0.437548     0.063592 -0.501141
3                    medical history osa  0.428262     0.035969 -0.464232
4                    history sleep apnea  0.425840     0.208714 -0.634554
5                    sleep apnea patient  0.405966     0.288396 -0.694361
6               sleep apnea hypertension  0.400078     0.186035 -0.586112
7                    obesity sleep apnea  0.389141     0.126252 -0.515393
8                       sleep apnea does  0.370227     0.179196 -0.549424
9                     sleep apnea social  0.362949     0.125535 -0.488484
10                  apnea social history  0.354857     0.133159 -0.488016
11             obesity obstructive sleep  0.350516     0.160121 -0.510637
12              asthma obstructive sleep  0.316780    -0.045840 -0.270940
13          medical history hypertension  0.306888    -0.107720 -0.199168
14                     sleep apnea bipap  0.306595     0.528956 -0.835551
15                  taking narcotic pain  0.299215    -0.172460 -0.126755
16                outpatient sleep study  0.293470     0.258038 -0.551508
17                   sleep apnea obesity  0.282770     0.201727 -0.484497
18                         does use cpap  0.281947     0.280900 -0.562847
19                         osa cpap home  0.273352     0.125525 -0.398877
20                       apnea cpap home  0.271354     0.228949 -0.500303
21                      sleep apnea home  0.269015     0.173819 -0.442833
22      impression bibasilar atelectasis  0.255298    -0.039928 -0.215369
23                         osa uses cpap  0.255112     0.099934 -0.355046
24           congestion pleural effusion  0.243848    -0.135554 -0.108294
25  hypertension hyperlipidemia diabetes  0.243481    -0.141759 -0.101723
26         pneumonia vascular congestion  0.243465    -0.101840 -0.141625
27              increased abdominal pain  0.235939    -0.100406 -0.135533
28                    given body habitus  0.235538     0.089228 -0.324766
29                       sleep apnea osa  0.235140     0.149801 -0.384941
30                 sleep apnea requiring  0.227044    -0.035456 -0.191587
31                    sleep apnea asthma  0.219448     0.054621 -0.274069
32             evidence congestive heart  0.216929    -0.113297 -0.103632
33                        apnea does use  0.216683     0.023540 -0.240223
34         ambulating voiding assistance  0.212237    -0.049151 -0.163086
35    pulmonary vasculature unremarkable  0.211556    -0.078465 -0.133091
36          endotracheal tube terminates  0.207845    -0.086113 -0.121732
37                   sleep apnea history  0.207120     0.113634 -0.320754
38                sleep apnea depression  0.200141     0.088079 -0.288220
39        medical history hyperlipidemia  0.200043    -0.088165 -0.111879
40                  possible sleep apnea  0.198890    -0.070825 -0.128065
41           admission albuterol sulfate  0.196340    -0.044713 -0.151627
42      hypercholesterolemia sleep apnea  0.193582     0.098582 -0.292164
43           medical history obstructive  0.191195     0.088603 -0.279798
44                          pt home cpap  0.191111    -0.029020 -0.162091
45                 levothyroxine 150 mcg  0.190954    -0.123277 -0.067677
46                         osa home cpap  0.189884     0.217484 -0.407368
47                  oriented x3 nonfocal  0.188674    -0.088189 -0.100485
48                      apnea cpap night  0.188098    -0.018339 -0.169759
49                     bupropion hcl 150  0.188018    -0.029552 -0.158466